blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('',home,name='home'),
    path('menu/',menu,name='menu'),
    path('logpage/',logpage,name='logpage'),
    path('signup/',signup,name='signup'),
    path('login/',login,name='login'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('api-auth/', include('rest_framework.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.



class Fruit(models.Model):
    name = models.CharField(max_length=200, null = True , blank= True)
    price = models.CharField(max_length=20, null = True , blank= True)
    available = models.CharField(max_length=20, null = True , blank= True)
    description = models.TextField(null = True , blank= True)
    image = models.ImageField(upload_to='images/', verbose_name=('Image'), blank=True, null=True)
    STATUS_CHOICE = (
        ('m' , 'موجود'),
        ('n','ناموجود')
    )
    status = models.CharField(max_length=1,choices=STATUS_CHOICE)


    def __str__(self):
        return self.name



class Vegtabale(models.Model):
    name = models.CharField(max_length=200, null = True , blank= True)
    price = models.CharField(max_length=20, null = True , blank= True)
    available = models.CharField(max_length=20, null = True , blank= True)
    description = models.TextField(null = True , blank= True)
    image = models.ImageField(upload_to='images/', verbose_name=('Image'), blank=True, null=True)
    STATUS_CHOICE = (
        ('m' , 'موجود'),
        ('n','ناموجود')
    )
    status = models.CharField(max_length=1,choices=STATUS_CHOICE)


    def __str__(self):
        return self.name

blog/views.py
from django.http.response import HttpResponse
from .models import *
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib import auth
from django.views.decorators.csrf import csrf_exempt
# Create your views here.




@csrf_exempt    
def home(request):
    data = Fruit.objects.all()
    size = len(data)
    if size>=3:
        context = {
            'fruits':[
                {
                    'name': data[0].name,
                    'price' : data[0].price,
                    'img' : data[0].image
                },
                {
                    'name': data[1].name,
                    'price' : data[1].price,
                    'img' : data[1].image
                },
                {
                    'name': data[2].name,
                    'price' : data[2].price,
                    'img' : data[2].image
                },
            ]
        }
    elif size==2:
        context = {
            'fruits':[
                {
                    'name': data[0].name,
                    'price' : data[0].price,
                    'img' : data[0].image
                },
                {
                    'name': data[1].name,
                    'price' : data[1].price,
                    'img' : data[1].image
                },
            ]
        }
    elif size==1:
        context = {
            'fruits':[
                {
                    'name': data[0].name,
                    'price' : data[0].price,
                    'img' : data[0].image
                },
            ]
        }
    else:
        return HttpResponse('database is empty. please add fruit',status =400)
    return render(request,'home.html',context= context)

def menu(request):
    fruits = Fruit.objects.all()
    vegtabales = Vegtabale.objects.all()
    context = {
        'fruits' : fruits,
        'vegtabales' : vegtabales,
    }
    return render(request,'menu.html',context=context)



def logpage(request):
    return render(request,'login.html')



def signup(request):
    if request.method == "POST":
        if request.POST['password1'] == request.POST['password2']:
            try:
                User.objects.get(username = request.POST['username'])
                return render (request,'login.html', {'error':'Username is already taken!'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'],password=request.POST['password1'])
                auth.login(request,user)
                return redirect('blog:home')
        else:
            return render (request,'login.html', {'error':'Password does not match!'})
    else:
        return render(request,'login.html')



def login(request):
    if request.method == 'POST':
        user = User.objects.filter(username=request.POST['username']).first()
        print('user : ',user)
        if user.check_password(request.POST['password']):
            auth.login(request,user)
            return redirect('blog:home')
        else:
            return render (request,'login.html', {'error':'Username or password is incorrect!'})
    else:
        return render(request,'blog:home')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
    return redirect('home')

blog/templates/home.html
<!DOCTYPE html>
<html lang="en">
     <head>
     <title>خانه</title>
     <meta charset="utf-8">
     <link rel="icon" href="../static/images/favicon.ico">
     <link rel="shortcut icon" href="../static/images/favicon.ico" />
     <link rel="stylesheet" href="../static/css/style.css">
     <script src="../static/js/jquery.js"></script>
     <script src="../static/js/jquery-migrate-1.1.1.js"></script>
     <script src="../static/js/jquery.equalheights.js"></script>
     <script src="../static/js/jquery.ui.totop.js"></script>
     <script src="../static/js/jquery.easing.1.3.js"></script>
     <script>
        $(document).ready(function(){
          $( ".block1" ).mouseover(function() {
            $(this).addClass( "blur" );
          });
          $( ".block1" ).mouseout(function() {
            $(this).removeClass( "blur" );
          });
          $().UItoTop({ easingType: 'easeOutQuart' });
        }) 
     </script>
     <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>
    <![endif]-->
    <!--[if lt IE 9]>
    
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie.css">
    <![endif]-->
    <!--[if lt IE 10]>
      <link rel="stylesheet" media="screen" href="css/ie1.css">
    <![endif]-->
    
     </head>
     <body class="page1">

<!--==============================header=================================-->
 <header> 
  <div class="container_12">
   <div class="grid_12"> 
    <div class="socials">
      <a href="#"></a>
      <a href="#"></a>
      <a href="#"></a>
      <a href="#" class="last"></a>
    </div>
    <h1><a href="{% url 'blog:home' %}"><img class="logo" src="../static/images/logo5.jpg" alt="Boo House"></a> </h1>
    <div class="menu_block">


    <nav id="bt-menu" class="bt-menu">
        <a href="#" class="bt-menu-trigger"><span>منو</span></a>
        <ul>
          <li class="current bt-icon "><a href="{% url 'blog:home' %}">خانه</a></li>
         <li class="bt-icon"><a href="{% url 'blog:logpage' %}">ورود</a></li>
         <li class="bt-icon"><a href="{% url 'blog:menu' %}">منو</a></li>
         <li class="bt-icon"><a href="index-3.html">بلاگ</a></li>
         <li class="bt-icon"><a href="index-4.html">سبد خرید</a></li>
         <li class="bt-icon"><a href="index-5.html">ارتباط با ما</a></li>
        </ul>
      </nav>
    
 <div class="clear"></div>
</div>
<div class="clear"></div>
          </div>
      </div>
</header>

<!--==============================Content=================================-->

<div class="content"><div class="ic"><!--More Website Templates @ TemplateMonster.com - December 02, 2013!--></div>
{% csrf_token %}
{% for fruit in fruits %}
<a href="{% url 'blog:menu' %}" class="block1">
  <img src="{{fruit.img.url}}" alt="">
  <span class="price"><span>{{fruit.name}}</span><span> {{fruit.price}} هزار <small> تومان</small></span><strong></strong></span>
</a>
{%endfor%}
  <div class="container_12">
    <div class="grid_12">
      <h3>میوه های جدید</h3>
    </div>
    <div class="grid_3">
      <div class="box maxheight">
        <img src="../static/images/pine.png" alt="">
        <div class="title">آناناس</div>
        <div class="truncate">
        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
         چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.
          کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد.
           در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارتها و شرایط سخت ایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. 
      </div>
        <a href="#">جزئیات بیشتر </a>
      </div>
    </div>
    <div class="grid_3">
      <div class="box maxheight">
        <img src="../static/images/mango.jpg" alt="">
        <div class="title">انبه</div>
        <div class="truncate">
        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
         چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.
          کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد.
           در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارتها و شرایط سخت ایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. 
          </div>
        <a href="#">جزئیات بیشتر </a>
      </div>
    </div>
    <div class="grid_3">
      <div class="box maxheight">
        <img src="../static/images/peach.jpg" alt="">
        <div class="title">هلو</div>
        <div class="truncate">
        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
         چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.
          کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد.
           در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارتها و شرایط سخت ایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. 
          </div>
        <a href="#">جزئیات بیشتر </a>
      </div>
    </div>
    <div class="grid_3">
      <div class="box maxheight">
        <img src="../static/images/straw.jpg" alt="">
        <div class="title">توت فرنگی</div>
        <div class="truncate">
        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
         چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.
          کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد.
           در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارتها و شرایط سخت ایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. 
          </div>
        <a href="#">جزئیات بیشتر </a>
      </div>
    </div>
  </div>
</div>

<!--==============================footer=================================-->

<footer>    
  <div class="container_12">
    <div class="grid_6 prefix_3">
      <a href="{% url 'blog:home' %}" class="f_logo"><!--<img src="../static/images/f_logo.png" alt="">--></a>
      <div class="copy">
      &copy; 2021 | <a href="#">Privacy Policy</a> <br> Website   designed by midxdle
      </div>
    </div>
  </div>
</footer>
     <script>
      $(document).ready(function(){ 
         $(".bt-menu-trigger").toggle( 
          function(){
            $('.bt-menu').addClass('bt-menu-open'); 
          }, 
          function(){
            $('.bt-menu').removeClass('bt-menu-open'); 
          } 
        ); 
      }) 
    </script>
</body>
</html>

blog/templates/login.html
<!DOCTYPE html>
<html lang="en">
     <head>
     <title>ورود</title>
     <meta charset="utf-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
	   <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="icon" href="../static/images/favicon.ico">
     <link rel="shortcut icon" href="../static/images/favicon.ico" />
     <link type="text/css" href="../static/css/bootstrap-rtl.min.css" rel="stylesheet">
     <link type="text/css" href="../static/css/font-awesome.min.css" rel="stylesheet" />
     <script src="../static/js/jquery.js"></script>
     <script src="../static/js/jquery-3.1.1.min.js"></script>
     <script src="../static/js/bootstrap.min.js"></script>
     <script src="../static/js/jquery-migrate-1.1.1.js"></script>
     <script src="../static/js/jquery.equalheights.js"></script>
     <script src="../static/js/jquery.ui.totop.js"></script>
     <script src="../static/js/jquery.easing.1.3.js"></script>
     <script>
        $(document).ready(function(){

          $().UItoTop({ easingType: 'easeOutQuart' });
        }) 
     </script>
     <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>

    <![endif]-->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie.css">
    <![endif]-->
    <!--[if lt IE 10]>
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie1.css">
    <![endif]-->
    
     </head>
     <body  class="">

<!--==============================header=================================-->
 <header> 
  <link rel="stylesheet" href="../static/css/style.css">
  <div class="container_12">
   <div class="grid_12"> 
    <div class="socials">
      <a href="#"></a>
      <a href="#"></a>
      <a href="#"> </a>
      <a href="#" class="last"></a>
    </div>
    <h1><a href="{% url 'blog:home' %}"><img class="logo" src="../static/images/logo3.jpg" alt="Boo House"></a> </h1>
    <div class="menu_block">


    <nav id="bt-menu" class="bt-menu">
        <a href="#" class="bt-menu-trigger"><span>منو</span></a>
        <ul>
          <li class="bt-icon "><a href="{% url 'blog:home' %}">خانه</a></li>
         <li class="current bt-icon"><a href="{% url 'blog:logpage' %}">ورود</a></li>
         <li class="bt-icon"><a href="{% url 'blog:menu' %}">منو</a></li>
         <li class="bt-icon"><a href="index-3.html">بلاگ</a></li>
         <li class="bt-icon"><a href="index-4.html">سبد خرید</a></li>
         <li class="bt-icon"><a href="index-5.html">ارتباط با ما</a></li>
        </ul>
      </nav>
    
 <div class="clear"></div>
</div>
<div class="clear"></div>
          </div>
      </div>
</header>


<!--==============================Content=================================-->
<link type="text/css" href="../static/css/styless.css" rel="stylesheet" /> 
<div id="login" class="container">
  <div class="d-flex justify-content-center h-100">
    <div class="card">
      <div class="card-header">
        <h2>ورود</h2>
      </div>
      <div class="card-body">
        <form method = "POST" action="{% url 'blog:login' %}">
          {% csrf_token %}
          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text input-icon"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" class="form-control" id="txt-username" placeholder="نام کاربری" name="username">
          </div>
          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text input-icon"><i class="fas fa-key"></i></span>
            </div>
            <input type="password" class="form-control" id="txt-password" placeholder="رمز عبور" name="password">
          </div>
          <div class="row align-items-center remember">
            <input type="checkbox">مرا بخاطر بسپار
          </div>
          <div class="form-group">
            <input type="submit" value="ورود" class="btn float-right login_btn">
          </div>
        </form>
      </div>
      <div class="card-footer">
        <div class="d-flex justify-content-center links">
          هنوز ثبت نام نکرده اید ؟<a onclick="document.getElementById('signup').style.display='block'; document.getElementById('login').style.display='none';" href="#">ثبت نام</a>
        </div>
        <div class="d-flex justify-content-center">
          <a href="#">بازگردانی رمز عبور !</a>
        </div>
      </div>
    </div>
  </div>
  </div>

  <!--SIGN UP-->

  <div id="signup" style="display: none;" class="container">
  <div class="d-flex justify-content-center h-100">
    <div class="card">
      <div class="card-header">
        <h2>ثبت نام</h2>
      </div>
      <div class="card-body">
        <form method = "POST" action="{% url 'blog:signup' %}">
          {% csrf_token %}
          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text input-icon"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" class="form-control" id="txt-username" placeholder="نام کاربری" name="username">
          </div>
          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text input-icon"><i class="fas fa-key"></i></span>
            </div>
            <input type="password" class="form-control" id="txt-password" placeholder="رمز عبور" name="password1">
          </div>
          <div class="input-group form-group">
            <div class="input-group-prepend">
              <span class="input-group-text input-icon"><i class="fas fa-key"></i></span>
            </div>
            <input type="password" class="form-control" id="txt-password" placeholder="تکرار رمز عبور" name="password2">
          </div>
          <div class="form-group">
            <input type="submit" value="ثبت نام" class="btn float-right login_btn">
          </div>
        </form>
      </div>
      <div class="card-footer">
        <div class="d-flex justify-content-center links">
          آیا ثبت نام کرده اید؟<a onclick="document.getElementById('signup').style.display='none'; document.getElementById('login').style.display='block';" href="#">ورود</a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<!--==============================footer=================================-->

<footer>    
  <div class="container_12">
    <div class="grid_9 prefix_3">
      <a href="index.html" class="f_logo"><!--<img src="images/f_logo.png" alt="">--></a>
      <div class="copy">
      &copy; 2021 | <a href="#">Privacy Policy</a> <br> Website   designed by midxdle</a>
      </div>
    </div>
  </div>
</footer>
      <script>
      $(document).ready(function(){ 
         $(".bt-menu-trigger").toggle( 
          function(){
            $('.bt-menu').addClass('bt-menu-open'); 
          }, 
          function(){
            $('.bt-menu').removeClass('bt-menu-open'); 
          } 
        ); 
      }) 
    </script>
</body>

</html>

blog/templates/menu.html
<!DOCTYPE html>
<html lang="en">
     <head>
     <title>منو</title>
     <meta charset="utf-8">
     <link rel="shortcut icon" href="../static/images/favicon.ico" />
     <link rel="icon" href="../static/images/favicon.ico">
     <link rel="stylesheet" href="../static/css/touchTouch.css">
     <link rel="stylesheet" href="../static/css/style.css">
     <script src="../static/js/jquery.js"></script>
     <script src="../static/js/jquery-migrate-1.1.1.js"></script>
     <script src="../static/js/jquery.equalheights.js"></script>
     <script src="../static/js/jquery.ui.totop.js"></script>
     <script src="../static/js/jquery.tabs.min.js"></script>
     <script src="../static/js/touchTouch.jquery.js"></script>
     <script src="../static/js/jquery.easing.1.3.js"></script>
     <script>
        $(document).ready(function(){

          $().UItoTop({ easingType: 'easeOutQuart' });
         $('.gallery a.gal').touchTouch();
         
       }) 
     </script>
     <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>

    <![endif]-->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie.css">
    <![endif]-->
    <!--[if lt IE 10]>
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie1.css">
    <![endif]-->
    
     </head>
     <body  class="">

<!--==============================header=================================-->
 <header> 
  <div class="container_12">
   <div class="grid_12"> 
    <div class="socials">
      <a href="#"></a>
      <a href="#"></a>
      <a href="#"> </a>
      <a href="#" class="last"></a>
    </div>
    <h1><a href="{% url 'blog:home' %}"><img class="logo" src="../static/images/logo3.jpg" alt="Boo House"></a> </h1>
    <div class="menu_block">


    <nav id="bt-menu" class="bt-menu">
        <a href="#" class="bt-menu-trigger"><span>منو</span></a>
        <ul>
          <li class="bt-icon "><a href="{% url 'blog:home' %}">خانه</a></li>
         <li class="bt-icon"><a href="{% url 'blog:logpage' %}">ورود</a></li>
         <li class="current bt-icon"><a href="{% url 'blog:menu' %}">منو</a></li>
         <li class="bt-icon"><a href="index-3.html">بلاگ</a></li>
         <li class="bt-icon"><a href="index-4.html">سبد خرید</a></li>
         <li class="bt-icon"><a href="index-5.html">ارتباط با ما</a></li>
        </ul>
      </nav>
    
 <div class="clear"></div>
</div>
<div class="clear"></div>
          </div>
      </div>
</header>

<!--==============================Content=================================-->

<div class="content"><div class="ic"><!--More Website Templates @ TemplateMonster.com - December 02, 2013!--></div>
  <div class="container_12">
    <div class="grid_12">
      <h3 class="head2">محصولات ما</h3>
    </div>  
    
    <div class="tabs tb gallery">
             <div class="div-nav  ">
             <div class="grid_12">
                 <ul class="nav">
                    <li class="selected"><a href="#tab-1" class="">میوه ها</a></li>
                    <li><a href="#tab-2">سبزیجات</a></li>
                 </ul>
             </div>    
             </div>

             <div class="div-tabs">
              <div  id="tab-1" class="tab-content gallery1">
                  {% for fruit in fruits %}
                  <div class="grid_3">
                    <a href="{{fruit.image.url}}" class="gal"><img src="{{fruit.image.url}}" alt=""><span></span></a>
                    <div class="col2"><span class="col3"><a href="#">{{fruit.name}} </a></span> {{fruit.price}} هزار تومان</div>
                  </div>
                  {% endfor %}
              </div>

              <div id="tab-2" class="tab-content gallery2">
                  <div class="clear"></div>
                  {% for vegtabale in vegtabales %}
                  <div class="grid_3">
                    <a href="{{vegtabale.image.url}}" class="gal"><img src="{{vegtabale.image.url}}" alt=""><span></span></a>
                    <div class="col2"><span class="col3"><a href="#">{{vegtabale.name}} </a></span> {{vegtabale.price}} هزار تومان</div>
                  </div>
                  {% endfor %}
              </div>
              </div>
             </div>
        </div>
  </div>
</div>

<!--==============================footer=================================-->

<footer>    
  <div class="container_12">
    <div class="grid_6 prefix_3">
      <a href="{% url 'blog:home' %}" class="f_logo"><!--<img src="images/f_logo.png" alt="">--><span></span></a>
    </div>
  </div>
</footer>
       <script>
      $(document).ready(function(){ 
         $(".bt-menu-trigger").toggle( 
          function(){
            $('.bt-menu').addClass('bt-menu-open'); 
          }, 
          function(){
            $('.bt-menu').removeClass('bt-menu-open'); 
          } 
        ); 
      }) 
    </script>
</body>

</html>